name: Update Depedencies

on:
  push:
    branches:
      - TrueNAS
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Build Dependencies
        run: |
          /bin/bash -c 'for chart in charts/*/*; do if [[ -d $chart ]]; then cd $chart && helm dependency update; fi; done'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update app depedencies
